### ISSUE TITLE
Подписать бы репозиторий?

### ISSUE THREAD

**Issue by justjune** [FallenEvill/UnityPM2021#1]
Чтобы мне каждый раз не искать автора....

**Comment by justjune** [comment]
Еще, вероятно, разумно в репозиторий просто складывать папки новых проектов, а не заводить новых репозиториев.

**Comment by justjune** [comment]
Кроме того, если в проекте более одной сцены, имеет смысл указать, какая из них главная, чтобы мне не приходилось искать. (Мог не зачесть эту работу.)

**Comment by FallenEvill** [comment]
Вроде бы сделал теперь как надо.
